### ISSUE TITLE
Regression in 3.12.7

### ISSUE THREAD

**Issue by marselester** [mindflayer/python-mocket#237]
Hi Giorgio. Thank you for your work on this library!

It looks like there was a breaking change in https://github.com/mindflayer/python-mocket/compare/3.12.6...3.12.7:

- https://github.com/maxmind/GeoIP2-python/actions/runs/9148591197/job/25152243949#step:5:1083
- https://github.com/maxmind/minfraud-api-python/actions/runs/9225347716/job/25382643724

**Comment by mindflayer** [comment]
Hi @marselester, thanks for opening this issue.
There is something going on with `aiohttp` I still don't fully understand, but I am aware of it.
So far my investigation brought me to see very strong similarities with https://github.com/aio-libs/aiohttp/issues/5582.
The latest version of Mocket was a big refactoring, mostly meant to fix https://github.com/mindflayer/python-mocket/pull/234/, and I strongly believe there is nothing wrong with Mocket itself, but of course I am open to help with this.

**Comment by marselester** [comment]
Thank you for looking into this issue ❤️

**Comment by mindflayer** [comment]
Hey @marselester, if you manage to write a few lines able to replicate the issue I'll be more than happy to help with that, even if I suspect it's not related to Mocket itself.

**Comment by marselester** [comment]
I took an example from your README and it also failed with `asyncio.exceptions.TimeoutError`.

```sh
(venv) $ python t.py
```

<details>

<summary>Test</summary>

```python
import json

import aiohttp
import asyncio
import unittest

from mocket.plugins.httpretty import httpretty, httprettified


class AioHttpEntryTestCase(unittest.TestCase):
    @httprettified
    def test_https_session(self):
        url = 'https://httpbin.org/ip'
        httpretty.register_uri(
            httpretty.GET,
            url,
            body=json.dumps(dict(origin='127.0.0.1')),
        )

        async def main(l):
            async with aiohttp.ClientSession(
                loop=l, timeout=aiohttp.ClientTimeout(total=3)
            ) as session:
                async with session.get(url) as get_response:
                    assert get_response.status == 200
                    assert await get_response.text() == '{"origin": "127.0.0.1"}'

        loop = asyncio.new_event_loop()
        loop.set_debug(True)
        loop.run_until_complete(main(loop))


if __name__ == '__main__':
    unittest.main()
```

</details>

<details>

<summary>Trace</summary>

```
/blah/.pyenv/versions/3.10.13/lib/python3.10/asyncio/selector_events.py:746: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  self._protocol = None
ResourceWarning: Enable tracemalloc to get the object allocation traceback
E
======================================================================
ERROR: test_https_session (__main__.AioHttpEntryTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/blah/blah/venv/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/blah/blah/venv/lib/python3.10/site-packages/mocket/mocket.py", line 736, in wrapper
    return test(*args, **kwargs)
  File "/blah/blah/t.py", line 30, in test_https_session
    loop.run_until_complete(main(loop))
  File "/blah/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/blah/blah/t.py", line 24, in main
    async with session.get(url) as get_response:
  File "/blah/blah/venv/lib/python3.10/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
  File "/blah/blah/venv/lib/python3.10/site-packages/aiohttp/client.py", line 608, in _request
    await resp.start(conn)
  File "/blah/blah/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 971, in start
    with self._timer:
  File "/blah/blah/venv/lib/python3.10/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

----------------------------------------------------------------------
Ran 1 test in 3.011s

FAILED (errors=1)
```

</details>

**Comment by mindflayer** [comment]
OK, there is indeed something strange when using `aiohttp` with HTTPS urls.

**Comment by mindflayer** [comment]
Here is a version which fixes it: https://pypi.org/project/mocket/3.12.8/

**Comment by mindflayer** [comment]
Here is a version which fixes it: https://pypi.org/project/mocket/3.12.8/
