### ISSUE TITLE
MocketSocket doesn't support SSL connections

### ISSUE THREAD

**Issue by bjmc** [mindflayer/python-mocket#3]
It looks like MocketSocket can't be wrapped completely by `SSLSocket`

``` python
>>> import requests
>>> from mocket.mocket import Mocket
>>> Mocket.enable()
>>> requests.get('https://httpbin.org')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bjmc/Sandbox/vcrpy/.env/local/lib/python2.7/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/home/bjmc/Sandbox/vcrpy/.env/local/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bjmc/Sandbox/vcrpy/.env/local/lib/python2.7/site-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bjmc/Sandbox/vcrpy/.env/local/lib/python2.7/site-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "/home/bjmc/Sandbox/vcrpy/.env/local/lib/python2.7/site-packages/requests/adapters.py", line 291, in send
    timeout=timeout
  File "/home/bjmc/Sandbox/vcrpy/.env/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 428, in urlopen
    body=body, headers=headers)
  File "/home/bjmc/Sandbox/vcrpy/.env/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 280, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/home/bjmc/Sandbox/vcrpy/.env/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 107, in connect
    ssl_version=resolved_ssl_version)
  File "/home/bjmc/Sandbox/vcrpy/.env/local/lib/python2.7/site-packages/requests/packages/urllib3/util.py", line 378, in ssl_wrap_socket
    ssl_version=ssl_version)
  File "/usr/lib/python2.7/ssl.py", line 440, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 168, in __init__
    socket.__init__(self, _sock=sock._sock)
  File "/usr/lib/python2.7/socket.py", line 190, in __init__
    setattr(self, method, getattr(_sock, method))
AttributeError: 'MocketSocket' object has no attribute 'recv'
```

**Comment by bjmc** [comment]
Thanks! :champagne:

**Comment by mindflayer** [comment]
@bjmc are you still using _mocket_?

**Comment by bjmc** [comment]
Unfortunately, no. Without this feature, it wasn't helpful for me. I might have another look at it, now, but the project for which I was originally considering `mocket` has ended.

**Comment by mindflayer** [comment]
I know it took forever, and I am really sorry.
Said this, the only big thing missing is now the documentation, but I would like to invest time on showing how to mock something non-HTTP. On the other side, the last releases are supporting sockets on _gevent_, _asyncio_/_aiohttp_ and _pypy_.
