### ISSUE TITLE
Problem related to SSL and Python 3.7

### ISSUE THREAD

**Issue by sentry0** [mindflayer/python-mocket#79]
I'm attempting to use Mocket in an application that needs to retrieve an auth token using REST call to a remote endpoint.  This call is throwing the following error:
```
super(SSLSocket, self).__init__(**kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
```
Everything works fine without Mocket.enable() being called, as soon as I enable it the program will crash with that error.

Any idea what I need to do to get Mocket working?

**Comment by mindflayer** [comment]
Hi @sentry0, are you able to produce a code snippet which fails with the same error? In that case I'd be able to debug the problem and try to fix it.

**Comment by mindflayer** [comment]
No info provided, in case feel free to open a new issue.

**Comment by thedrow** [comment]
This happens on Python 3.7.
Also see https://github.com/gabrielfalcao/HTTPretty/issues/337

**Comment by mindflayer** [comment]
Thanks, @thedrow.

**Comment by ekor15** [comment]
same here - simple code to reproduce:

```python
from unittest import TestCase
import requests
from mocket import mocketize
from mocket.mockhttp import Entry


class TestShutterstockClient(TestCase):
  @mocketize
  def test_simple_mock(self):
    Entry.single_register(Entry.GET, 'https://google.co.il', body='lalallaa', headers={'content-type': 'application/json'})
    response = requests.get('https://google.co.il')
    print(response)
```

```pytb
/Users/elirans/projects/media-search/run/lib/python3.7/site-packages/mocket/mocket.py:468: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(responses, collections.Iterable) or isinstance(responses, basestring):
/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py:643: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 0)>
  outcome.errors.clear()

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "</Users/elirans/projects/media-search/run/lib/python3.7/site-packages/decorator.py:decorator-gen-1>", line 2, in test_simple_mock
  File "/Users/elirans/projects/media-search/run/lib/python3.7/site-packages/mocket/mocket.py", line 524, in wrapper
    t(*args, **kw)
  File "/Users/elirans/projects/media-search/tests/media_search_tests/services/search/test_shutterstock_client.py", line 54, in test_simple_mock
    response = requests.get('https://google.co.il')
  File "/Users/elirans/projects/media-search/run/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/elirans/projects/media-search/run/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/elirans/projects/media-search/run/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/elirans/projects/media-search/run/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/elirans/projects/media-search/run/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/elirans/projects/media-search/run/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/elirans/projects/media-search/run/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/Users/elirans/projects/media-search/run/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/Users/elirans/projects/media-search/run/lib/python3.7/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/Users/elirans/projects/media-search/run/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 817, in _create
    super(SSLSocket, self).__init__(**kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by mindflayer** [comment]
Mocket now fully supports Python 3.7:
https://pypi.org/project/mocket/3.7.0/
