### ISSUE TITLE
redis.exceptions.ConnectionError: Connection not ready with redis==3.2.0

### ISSUE THREAD

**Issue by hulucc** [mindflayer/python-mocket#85]

**Comment by mindflayer** [comment]
Can you add more details? Python 3.6 is supposed to work with `mocket`.

**Comment by hulucc** [comment]
![image](https://user-images.githubusercontent.com/4343900/54342082-8603ec00-4676-11e9-8d01-10be37d1a244.png)
![image](https://user-images.githubusercontent.com/4343900/54342093-8ef4bd80-4676-11e9-99fb-bd82f39c2d97.png)

**Comment by mindflayer** [comment]
I will have a look at it, but what is the purpose of mocking `FLUSHDB`?

**Comment by mindflayer** [comment]
So, the problem has something to do with the latest update of `redis`.
```(.venv) /tmp $ pip install redis==3.1.0
Collecting redis==3.1.0
  Downloading https://files.pythonhosted.org/packages/f1/19/a0282b77c23f9f9dbcc6480787a60807c78a45947593a02dbf026636c90d/redis-3.1.0-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 71kB 1.1MB/s 
Installing collected packages: redis
  Found existing installation: redis 3.2.0
    Uninstalling redis-3.2.0:
      Successfully uninstalled redis-3.2.0
Successfully installed redis-3.1.0
(.venv) /tmp $ python test.py 
(.venv) /tmp $ pip install redis==3.2.0
Collecting redis==3.2.0
  Using cached https://files.pythonhosted.org/packages/d0/8b/c43ef27d02382853b22c49bc41a8389e47d60811dd1d72b9a45bc905a5f8/redis-3.2.0-py2.py3-none-any.whl
Installing collected packages: redis
  Found existing installation: redis 3.1.0
    Uninstalling redis-3.1.0:
      Successfully uninstalled redis-3.1.0
Successfully installed redis-3.2.0
(.venv) /tmp $ python test.py 
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    r.flushdb()
  File "/tmp/.venv/lib/python3.6/site-packages/redis/client.py", line 950, in flushdb
    return self.execute_command('FLUSHDB', *args)
  File "/tmp/.venv/lib/python3.6/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/tmp/.venv/lib/python3.6/site-packages/redis/connection.py", line 1003, in get_connection
    raise ConnectionError('Connection not ready')
redis.exceptions.ConnectionError: Connection not ready
```

**Comment by mindflayer** [comment]
The `redis` module author is changing the behaviour that caused the problem with `mocket`, because also brought problems when the module is used together with `gevent` and `eventlet`. I hope this will be solved soon.
https://github.com/andymccurdy/redis-py/commit/acac4db0c064d2618d75f27a58384c97c16458fd#diff-b3be2d0fa4e0cf1f1c403f2de43ecdb4

**Comment by mindflayer** [comment]
Fixed: https://pypi.org/project/mocket/3.8.0/
